server:
  port: 8846
spring:
  application:
    name: auth-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 60.204.212.12:8848
security:
  oauth2:
    client:
      scope: all
      client-id: linter
      client-secret: linter
      authorized-grant-types: password
      access-token-validity-seconds: 864000
    authorization:
      check-token-access: permitAll() #允许任何人访问令牌检查端点
      token-key-access: permitAll() #允许任何人访问令牌密钥端点
      jwt:
        key-store: classpath:jwt.jks #定义JWT密钥的存储位置
        key-store-password: linter #访问jwt.jks文件密码
        key-alias: jwt #别名