server:
  port: 8450
spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: 60.204.212.12:8848
  data:
    mongodb:
      host: 60.204.212.12
      port: 27017
      database: chat_record
  jackson:
    default-property-inclusion: non_null
pulsar:
  host: 60.204.217.157:6650
  topic: chat
  subscription: chat