server:
  port: 8410
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: user-service
  redis:
    host: 60.204.212.12
  cloud:
    nacos:
      discovery:
        server-addr: 60.204.212.12:8848
  datasource:
    url: jdbc:mysql://localhost/doufenoasys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: helloworld
  jackson:
    default-property-inclusion: non_null
  cache:
    type: redis
    cache-names: permission-role